#staging.gocd.yaml
format_version: 1
environments:
  TASP_PRE:
    environment_variables:
    pipelines:
      - VitaDeployNoRebuild
      - VitaDeployRebuild
pipelines:
  VitaDeployNoRebuild: # definition of yaml-example pipeline
    group: TestYaml
    materials:
      tasp: # this is the name of material
        # keyword git says about type of material and url at once
        git: git@github.com:rubensan112/kubernetesMadridWeb.git
        branch: master

    stages: # list of stages in order
      - Build: # name of stage
          clean_workspace: false
          jobs:
            DockerBuild: # name of the job
              tasks:
                - exec: # indicates type of task
                    command: ls
                - exec: # indicates type of task
                   command: docker
                   arguments:
                    - image
                    - ls
                - script: |
                    docker rmi $(docker images -f "dangling=true" -q) --force
                    true
                - exec: # indicates type of task
                    command: docker
                    arguments:
                      - image
                      - ls
                - exec: # indicates type of task
                    command: docker-compose
                    arguments:
                      - build
      - Deploy:
          clean_workspace: false
          jobs:
            kubernetesDeploy:
              tasks:
                - script: |
                    kubectl delete svc django-service
                    kubectl delete deployments django
                    kubectl delete job django-pull
                    kubectl delete job django-migrations
                    sleep 5
                    kubectl create -f update/job-pull.yaml
                    sleep 6
                    kubectl create -f django/job-migrations.yaml
                    sleep 3
                    kubectl create -f django/deployment.yaml
                    sleep 2
                    kubectl create -f django/service.yaml

  VitaDeployRebuild: # definition of yaml-example pipeline
    group: TestYaml
    materials:
      tasp: # this is the name of material
        # keyword git says about type of material and url at once
        git: git@github.com:rubensan112/kubernetesMadridWeb.git
        branch: master

    stages: # list of stages in order
      - Deploy:
          clean_workspace: false
          jobs:
            kubernetesDeploy:
              tasks:
                - script: |
                    kubectl delete svc django-service
                    kubectl delete job django-pull
                    kubectl delete job django-migrations
                    kubectl create -f update/job-pull.yaml
                    sleep 6
                    kubectl create -f django/job-migrations.yaml
                    sleep 3
                    kubectl create -f django/service.yaml

