#staging.gocd.yaml
format_version: 1
environments:
  TASP_PRE:
    environment_variables:
    pipelines:
      - VitaTestBuild
pipelines:
  VitaTestBuild: # definition of yaml-example pipeline
    group: TestYaml
    materials:
      tasp: # this is the name of material
        # keyword git says about type of material and url at once
        git: git@github.com:rubensan112/GoCDMadridWeb.git
        branch: master

    stages: # list of stages in order
      - Build: # name of stage
          clean_workspace: false
          jobs:
            DockerBuild: # name of the job
              tasks:
                - exec: # indicates type of task
                   command: docker
                   arguments:
                    - image
                    - ls
                    - "--force-rm"
                    - "--no-cache"
