#staging.gocd.yaml
format_version: 1
environments:
  TASP_PRE:
    environment_variables:
    pipelines:
      - VitaTestBuild
      - Testing
pipelines:
  Testing: # definition of yaml-example pipeline
    group: TestYaml
    materials:
      tasp: # this is the name of material
        # keyword git says about type of material and url at once
        git: git@github.com:rubensan112/GoCDMadridWeb.git
        branch: master

    stages: # list of stages in order
      - Build: # name of stage
          clean_workspace: false
          jobs:
            DockerBuild: # name of the job
              tasks:
                - exec: # indicates type of task
                   command: printenv
  VitaTestBuild: # definition of yaml-example pipeline
    group: TestYaml
    materials:
      tasp: # this is the name of material
        # keyword git says about type of material and url at once
        git: git@github.com:rubensan112/madridWeb.git
        branch: master

    stages: # list of stages in order
      - Build: # name of stage
          clean_workspace: false
          jobs:
            DockerBuild: # name of the job
              tasks:
                - exec: # indicates type of task
                    command: ls
                - exec: # indicates type of task
                   command: docker
                   arguments:
                    - image
                    - ls
                - exec: # indicates type of task
                    command: docker-compose
                    arguments:
                      - build
                - exec: # indicates type of task
                    command: build2.sh
                - exec: # indicates type of task
                    command: docker-compose
                    arguments:
                      - up

